# Generated by Django 3.1.2 on 2020-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201023_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='newfield',
            field=models.CharField(default='newfield', max_length=255),
        ),
    ]
