# Generated by Django 3.1.2 on 2020-10-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
