# Generated by Django 3.1.2 on 2020-10-29 09:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.advertisement_image_file_path),
        ),
    ]
