# Generated by Django 3.1.2 on 2020-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classroom_comment_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
