# Generated by Django 3.1.2 on 2020-11-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201113_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='core.classroom'),
        ),
    ]
