# Generated by Django 3.1.2 on 2020-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
