# Generated by Django 3.1.2 on 2021-02-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210201_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('answerText', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionnarie',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Questionnarie',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questionchoice', to='core.question'),
        ),
    ]
